;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Ignitable",NewTagName="Attributes.Ignitable")
+GameplayTagRedirects=(OldTagName="CanSupercombine",NewTagName="Attributes.Supercombineable")
+GameplayTagRedirects=(OldTagName="ArmorType",NewTagName="Armor")
+GameplayTagRedirects=(OldTagName="DamageType",NewTagName="Damage")
+GameplayTagRedirects=(OldTagName="DamageType.Acid",NewTagName="Damage.Acid")
+GameplayTagRedirects=(OldTagName="DamageType.Explosive",NewTagName="Damage.Explosive")
+GameplayTagRedirects=(OldTagName="DamageType.Explosive.Grenade",NewTagName="Damage.Explosive.Grenade")
+GameplayTagRedirects=(OldTagName="DamageType.Explosive.Stationary",NewTagName="Damage.Explosive.Stationary")
+GameplayTagRedirects=(OldTagName="DamageType.Fire",NewTagName="Damage.Fire")
+GameplayTagRedirects=(OldTagName="DamageType.Fire.Environmental",NewTagName="Damage.Fire.Environmental")
+GameplayTagRedirects=(OldTagName="DamageType.Plasma",NewTagName="Damage.Plasma")
+GameplayTagRedirects=(OldTagName="DamageType.Puncture",NewTagName="Damage.Puncture")
+GameplayTagRedirects=(OldTagName="DamageType.Shock",NewTagName="Damage.Shock")
+GameplayTagRedirects=(OldTagName="DamageType.Slash",NewTagName="Damage.Slash")
+GameplayTagRedirects=(OldTagName="DamageType.Impact.Melee",NewTagName="Damage.Impact.Melee")
+GameplayTagRedirects=(OldTagName="DamageType.Impact.VehicleRam",NewTagName="Damage.Impact.VehicleRam")
+GameplayTagRedirects=(OldTagName="DamageType.Impact",NewTagName="Damage.Impact")
+GameplayTagRedirects=(OldTagName="ArmorType.Cloth",NewTagName="Armor.Cloth")
+GameplayTagRedirects=(OldTagName="ArmorType.Flesh",NewTagName="Armor.Flesh")
+GameplayTagRedirects=(OldTagName="ArmorType.Metal",NewTagName="Armor.Metal")
+GameplayTagRedirects=(OldTagName="ArmorType.Shield",NewTagName="Armor.Shield")
+GameplayTagRedirects=(OldTagName="CanInteract",NewTagName="Character.CanInteract")
+GameplayTagList=(Tag="AI.SmartObject",DevComment="")
+GameplayTagList=(Tag="Armor",DevComment="")
+GameplayTagList=(Tag="Armor.Cloth",DevComment="")
+GameplayTagList=(Tag="Armor.Flesh",DevComment="")
+GameplayTagList=(Tag="Armor.Metal",DevComment="")
+GameplayTagList=(Tag="Armor.Shield",DevComment="")
+GameplayTagList=(Tag="Attributes",DevComment="")
+GameplayTagList=(Tag="Attributes.Breathless",DevComment="")
+GameplayTagList=(Tag="Attributes.Danger",DevComment="Thigns characters should avoid")
+GameplayTagList=(Tag="Attributes.Ignitable",DevComment="Objects that can take fire damage")
+GameplayTagList=(Tag="Attributes.Invisible",DevComment="")
+GameplayTagList=(Tag="Attributes.Invulnerable",DevComment="")
+GameplayTagList=(Tag="Attributes.OpensDoors",DevComment="")
+GameplayTagList=(Tag="Attributes.ShowOnRadar",DevComment="")
+GameplayTagList=(Tag="Attributes.ShowOnRadar.Large",DevComment="")
+GameplayTagList=(Tag="Attributes.ShowOnRadar.Small",DevComment="")
+GameplayTagList=(Tag="Attributes.Stunned",DevComment="")
+GameplayTagList=(Tag="Attributes.Supercombineable",DevComment="Things that can be stuck and explode from needler projectiles")
+GameplayTagList=(Tag="Character.CanBreatheUnderwater",DevComment="")
+GameplayTagList=(Tag="Character.CanInteract",DevComment="")
+GameplayTagList=(Tag="Character.CanMelee",DevComment="")
+GameplayTagList=(Tag="Character.CanUseEquipment",DevComment="")
+GameplayTagList=(Tag="Character.CanUseGrenades",DevComment="")
+GameplayTagList=(Tag="Character.CanUseVehicles",DevComment="")
+GameplayTagList=(Tag="Character.CanUseWeapons",DevComment="")
+GameplayTagList=(Tag="Damage",DevComment="")
+GameplayTagList=(Tag="Damage.Acid",DevComment="")
+GameplayTagList=(Tag="Damage.Explosive",DevComment="")
+GameplayTagList=(Tag="Damage.Explosive.Grenade",DevComment="")
+GameplayTagList=(Tag="Damage.Explosive.Stationary",DevComment="")
+GameplayTagList=(Tag="Damage.Fire",DevComment="")
+GameplayTagList=(Tag="Damage.Fire.Environmental",DevComment="")
+GameplayTagList=(Tag="Damage.Impact.Melee",DevComment="")
+GameplayTagList=(Tag="Damage.Impact.VehicleRam",DevComment="")
+GameplayTagList=(Tag="Damage.Plasma",DevComment="")
+GameplayTagList=(Tag="Damage.Puncture",DevComment="")
+GameplayTagList=(Tag="Damage.Shock",DevComment="")
+GameplayTagList=(Tag="Damage.Slash",DevComment="")
+GameplayTagList=(Tag="Equipment.Defensive",DevComment="")
+GameplayTagList=(Tag="Equipment.Offensive",DevComment="")
+GameplayTagList=(Tag="Equipment.Utility",DevComment="")
+GameplayTagList=(Tag="Status",DevComment="")
+GameplayTagList=(Tag="Status.Bleeding",DevComment="")
+GameplayTagList=(Tag="Status.Concussed",DevComment="")
+GameplayTagList=(Tag="Status.OnFire",DevComment="")
+GameplayTagList=(Tag="Status.Poisoned",DevComment="")
+GameplayTagList=(Tag="Status.Shocked",DevComment="")
+GameplayTagList=(Tag="Status.Wet",DevComment="")

